[providers.cagelab-dev]
type     = "sftp"
host     = "cagelab-dev.cloud.lab"
user     = "cagelab"
port     = 22
key_file = "~/.ssh/cagelab"

[providers.cog5]
type     = "sftp"
host     = "cog5.cloud.lab"
user     = "cog5"
port     = 22
key_file = "~/.ssh/id_rsa"

[providers.cog21]
type     = "sftp"
host     = "cog21.cloud.lab"
user     = "cog"
port     = 22
key_file = "~/.ssh/id_rsa"

