# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

# https://yazi-rs.github.io/docs/configuration/overview

[mgr]
ratio			= [ 1, 3, 4 ]
sort_by			= "mtime"
sort_reverse	= true
sort_dir_first	= true
linemode		= "size_and_mtime"
show_symlink	= true

[preview]
wrap			= "yes"
tab_size		= 2
max_width		= 1000
max_height		= 1000

[opener]
play = [
	{ run = "mpv %s", desc = "mpv", orphan = true, for = "unix" },
	{ run = "vlc %s", desc = "vlc",  orphan = true, for = "unix" },
	{ run = '"C:\Program Files\mpv.exe" %s', desc = "mpv", orphan = true, for = "windows" },
	{ run = "mediainfo %s1; echo 'Press enter to exit'; read _", block = true, desc = "Show media info", for = "unix" },
	{ run = "mediainfo %s1 & pause", block = true, desc = "Show media info", for = "windows" },
]
edit = [
	{ run = "nvim %s", block = true, for = "unix", desc = "Edit with Neovim" },
	{ run = "code -w %s", block = true, desc = "Edit with VSCode" },
	{ run = "code %s", block = false, desc = "Edit with VSCode non-blocking" },
	{ run = "open -a 'Pixelmator Pro.app' %s", block = false, desc = "Edit with Pixelmator Pro", for = "macos" },
	{ run = "%EDITOR% %s", block = true, for = "windows" },
]
open = [
	{ run = "xdg-open %s1", desc = "Open" , orphan = true, for = "linux" },
	{ run = "open %s", desc = "Open", orphan = true, for = "macos" },
	{ run = "start %s", desc = "Open", orphan = true, for = "windows" },
	{ run = 'zathura "$@"', orphan = true, desc = "Open PDFs with Zathura", for = "unix" },
]
[open]
prepend_rules = [
	{ url = "*.json", use = "edit" },
	{ url = "*.md", use = "edit" },
	{ url = "*.mp4", use = "play" },
	{ url = "*.mkv", use = "play" },
	{ url = "*.avi", use = "play" },
	{ url = "*.mov", use = "play" },
	{ url = "*.webm", use = "play" },
	{ url = "*.flac", use = "play" },
	{ url = "*.mp3", use = "play" },
	{ url = "*.wav", use = "play" },
	{ url = "*.pdf", use = "open" },
	{ url = "*.png", use = ["open","edit"] },
	{ url = "*.txt", use = "edit" },
	# Multiple openers for a single rule
	{ url = "*.html", use = [ "open", "edit" ] },
]
