# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true
scan_timeout = 10
command_timeout = 750

[character] 
success_symbol = "[âª](bold green)"
error_symbol = "[â—](bold red)"

[username]
detect_env_vars = []
format = "[$user]($style) in "
style_root = "red bold"
style_user = "yellow bold"
show_always = false
disabled = false

[sudo]
disabled = false

[shlvl]
threshold = 2
symbol = "â†•ï¸ "
format = "[$symbol$shlvl]($style) "
repeat = false
repeat_offset = 0
style = "dimmed yellow"
disabled = false

[shell]
bash_indicator = "Î²"
zsh_indicator = "Î¶"
elvish_indicator = "Îµ"
style = "dimmed yellow"
disabled = false

[ruby]
format = "via [$symbol($version )]($style)"
version_format = "v${raw}"
symbol = "ğŸ® "

[hostname]
ssh_symbol = "ğŸŒ "
trim_at = "."
format = "[$ssh_symbol$hostname]($style) in "
style = "green dimmed bold"
ssh_only = false

[memory_usage]
threshold = 75
format = "via $symbol[$ram( | $swap)]($style) "
style = "white bold dimmed"
symbol = "ğŸ "
disabled = true

[directory]
read_only = "ğŸ”’"
read_only_style = "red"
truncation_symbol = "â€¦/"

[battery]
[[battery.display]]
threshold = 10
style = "bold red"
[[battery.display]]
threshold = 30
style = "bold yellow"
discharging_symbol = "âŒ"
