# Inserts a blank line between shell prompts
add_newline = true

[character] 
success_symbol = "[â–¶ï¸Ž](bold green)"
error_symbol = "[â–·](bold red)"

#[env_var]
#variable = "PLATFORM"
#default = ""

[shlvl]
symbol = "â†¯"
style = "dimmed yellow"
disabled = false

[shell]
bash_indicator = "â“‘"
zsh_indicator = "â“©"
elvish_indicator = "â“”"
style = "dimmed gray"
disabled = false

[hostname]
format = "[$hostname]($style) Â» "
ssh_only = false

[memory_usage]
disabled = false

[directory]
truncation_symbol = "â€¦/"

[battery]
[[battery.display]]
threshold = 10
style = "bold red"
[[battery.display]]
threshold = 30
style = "bold yellow"
discharging_symbol = "ðŸ’¦"
